// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
import fs from 'fs';
import path from 'path';
import { StateMachine, StateMachineProps } from '@matthewbonig/state-machine';
import { Construct } from 'constructs';
export interface BatchProcessorStateMachineOverrides {
  readonly 'Create Batch': Partial<{
    'Type': string;
    'Resource': string;
    'OutputPath': string;
    'Parameters': Partial<{
      'Payload.$': string;
      'FunctionName': string;
    }>;
    'Retry': Partial<[Partial<{
      'ErrorEquals': Partial<[string, string, string, string]>;
      'IntervalSeconds': number;
      'MaxAttempts': number;
      'BackoffRate': number;
    }>]>;
    'Next': string;
  }>;
  readonly 'Map': Partial<{
    'Type': string;
    'ItemProcessor': Partial<{
      'ProcessorConfig': Partial<{
        'Mode': string;
        'ExecutionType': string;
      }>;
      'StartAt': string;
      'States': Partial<{
        'Process Item': Partial<{
          'Type': string;
          'Resource': string;
          'OutputPath': string;
          'Parameters': Partial<{
            'Payload.$': string;
            'FunctionName': string;
          }>;
          'Retry': Partial<[Partial<{
            'ErrorEquals': Partial<[string, string, string, string]>;
            'IntervalSeconds': number;
            'MaxAttempts': number;
            'BackoffRate': number;
          }>]>;
          'End': Partial<{
          }>;
        }>;
      }>;
    }>;
    'End': Partial<{
    }>;
    'Label': string;
    'MaxConcurrency': number;
    'ItemReader': Partial<{
      'Resource': string;
      'ReaderConfig': Partial<{
        'InputType': string;
      }>;
      'Parameters': Partial<{
        'Bucket.$': string;
        'Key.$': string;
      }>;
    }>;
    'ItemBatcher': Partial<{
      'MaxItemsPerBatch': number;
    }>;
  }>;
}
export interface BatchProcessorStateMachineProps extends Omit<StateMachineProps, 'overrides' | 'definition'> {
  readonly overrides: Partial<BatchProcessorStateMachineOverrides>;
}
export class BatchProcessorStateMachine extends StateMachine {
  constructor(scope: Construct, id: string, props: BatchProcessorStateMachineProps) {
    super(scope, id, {
      ...props,
      definition: JSON.parse(fs.readFileSync(path.join(__dirname, 'batch-processor.workflow.json')).toString()),
    });
  }
}